name: Deploy to VPS on push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.49.224.185 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@13.49.224.185 << 'EOF'
            cd /home/project/Learning-docker
            docker pull vite-react-app
            docker build -t vite-react-app .
            docker run -d -p 80:80 vite-react-app
          EOF
